#!/bin/bash
# import-mcps.sh - Import MCPs from global Claude settings into project skills
# Usage: ./import-mcps.sh [--dry-run] [--backup]

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

# Paths
GLOBAL_SETTINGS="$HOME/.claude/settings.json"
PROJECT_SETTINGS=".claude/settings.json"
SKILLS_DIR="mcp-skills"
TEMPLATE_FILE="$SKILLS_DIR/_template.md"

# Flags
DRY_RUN=false
BACKUP=false

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --dry-run) DRY_RUN=true; shift ;;
    --backup) BACKUP=true; shift ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

echo ""
echo -e "${BLUE}╔════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║      MCP Skills - Import MCPs          ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════╝${NC}"
echo ""

# Check if global settings exist
if [[ ! -f "$GLOBAL_SETTINGS" ]]; then
  echo -e "${RED}✗${NC} Global settings not found: $GLOBAL_SETTINGS"
  exit 1
fi

# Check for jq
if ! command -v jq &> /dev/null; then
  echo -e "${RED}✗${NC} jq is required. Install with: brew install jq"
  exit 1
fi

# Create skills directory if needed
mkdir -p "$SKILLS_DIR"

# Backup if requested
if [[ "$BACKUP" == "true" && "$DRY_RUN" == "false" ]]; then
  BACKUP_FILE="$GLOBAL_SETTINGS.backup.$(date +%Y%m%d_%H%M%S)"
  cp "$GLOBAL_SETTINGS" "$BACKUP_FILE"
  echo -e "${GREEN}✓${NC} Backed up to: $BACKUP_FILE"
fi

# Extract MCP servers from global settings
echo -e "${BLUE}→${NC} Reading MCPs from global settings..."

# Get mcpServers object
MCP_SERVERS=$(jq -r '.mcpServers // {}' "$GLOBAL_SETTINGS")

if [[ "$MCP_SERVERS" == "{}" || "$MCP_SERVERS" == "null" ]]; then
  echo -e "${YELLOW}!${NC} No MCP servers found in global settings"
  exit 0
fi

# Count MCPs
MCP_COUNT=$(echo "$MCP_SERVERS" | jq -r 'keys | length')
echo -e "${GREEN}✓${NC} Found $MCP_COUNT MCP server(s)"
echo ""

# Process each MCP
echo "$MCP_SERVERS" | jq -r 'keys[]' | while read -r MCP_NAME; do
  SKILL_FILE="$SKILLS_DIR/${MCP_NAME}.md"

  # Get MCP config
  MCP_CONFIG=$(echo "$MCP_SERVERS" | jq -r --arg name "$MCP_NAME" '.[$name]')
  MCP_COMMAND=$(echo "$MCP_CONFIG" | jq -r '.command // "unknown"')
  MCP_ARGS=$(echo "$MCP_CONFIG" | jq -r '.args // [] | join(" ")')
  MCP_ENV=$(echo "$MCP_CONFIG" | jq -r '.env // {} | to_entries | map("- `\(.key)`: \(.value // "required")") | join("\n")')

  if [[ "$DRY_RUN" == "true" ]]; then
    echo -e "${YELLOW}[DRY RUN]${NC} Would create: $SKILL_FILE"
    echo "  Command: $MCP_COMMAND $MCP_ARGS"
    continue
  fi

  # Skip if skill already exists
  if [[ -f "$SKILL_FILE" ]]; then
    echo -e "${YELLOW}!${NC} Skipping (exists): $MCP_NAME"
    continue
  fi

  # Generate skill file
  cat > "$SKILL_FILE" << SKILL
---
skill_id: ${MCP_NAME}
mcp_server: ${MCP_NAME}
category: imported
tags: [mcp, auto-imported]
last_updated: $(date +%Y-%m-%d)
---

# ${MCP_NAME} MCP Skill

## Purpose

*Auto-imported from global Claude settings. Add description here.*

## MCP Server Configuration

**Command:** \`${MCP_COMMAND} ${MCP_ARGS}\`

**Environment Variables:**
${MCP_ENV:-"*None required*"}

## Tools Available

*Run \`/mcp-skills --discover ${MCP_NAME}\` to auto-discover tools.*

### tool_name

Description of what this tool does.

**Arguments:**
\`\`\`json
{
  "arg1": "string - description"
}
\`\`\`

**Example:**
\`\`\`
Use MCP tool ${MCP_NAME}:tool_name with {"arg1": "value"}
\`\`\`

## Common Issues

*Document common issues here as you discover them.*

## References

- [MCP Server Documentation](https://example.com)

---
*Auto-generated by mcp-skills import. Update this file with actual tool documentation.*
SKILL

  echo -e "${GREEN}✓${NC} Created: $SKILL_FILE"
done

echo ""
echo -e "${GREEN}✅ Import complete!${NC}"
echo ""
echo "Next steps:"
echo "  1. Run: ./scripts/sync-index.sh"
echo "  2. Edit skill files to add tool documentation"
echo "  3. Use: /mcp-skills --discover <name> to auto-discover tools"
echo ""
